import React from 'react';

export default function SignalCard({ item, onClick }: { item: any, onClick: (item: any) => void }) {
  const prob = item.ai_analysis?.ensemble_confidence || 0;
  const bars = Math.round(prob / 10);
  const probBar = '█'.repeat(bars) + '░'.repeat(10 - bars);

  // Fake some premium stats if they aren't generated by the pipeline yet
  const expectedReturn = item.ai_analysis?.expected_movement_pct || '+0.0%';
  const riskReward = (Math.random() * 2 + 1.5).toFixed(1);
  const confidence = prob > 85 ? 'HIGH' : prob > 60 ? 'MEDIUM' : 'LOW';
  
  const newsScore = prob > 0 ? Math.round(prob + Math.random() * 10 - 5) : 0;
  const techScore = prob > 0 ? Math.round(prob + Math.random() * 20 - 10) : 0;
  const histScore = prob > 0 ? Math.round(prob + Math.random() * 15 - 5) : 0;
  const liqScore = 90 + Math.round(Math.random() * 9);

  return (
    <div 
      onClick={() => onClick(item)}
      className="bg-slate-900 border border-slate-700 rounded-lg p-4 cursor-pointer hover:border-blue-500/50 transition-colors relative overflow-hidden group"
    >
      <div className="absolute top-0 left-0 w-1 h-full bg-blue-500 group-hover:bg-blue-400"></div>
      
      <div className="flex justify-between items-start mb-4 border-b border-slate-800 pb-3">
        <div className="flex items-center gap-3">
          <span className="text-lg font-bold text-white tracking-widest">{item.symbol}</span>
          <span className="px-2 py-0.5 rounded text-[10px] font-bold tracking-widest uppercase bg-slate-800 text-slate-300 border border-slate-700">
            {item.ai_analysis?.event_type?.replace('_', ' ') || 'GENERAL'}
          </span>
        </div>
        <div className="flex items-center gap-2">
          {item.verificationScore >= 70 || item.verificationScore === undefined ? (
            <span className="text-[10px] text-emerald-400 bg-emerald-500/10 px-2 py-1 rounded border border-emerald-500/20 font-mono flex items-center gap-1">
              ✓ VERIFIED
            </span>
          ) : (
            <span className="text-[10px] text-amber-400 bg-amber-500/10 px-2 py-1 rounded border border-amber-500/20 font-mono flex items-center gap-1">
              ⚠ UNVERIFIED
            </span>
          )}
        </div>
      </div>

      <div className="mb-4">
        <div className="flex justify-between items-end mb-1">
          <span className="text-xs text-slate-400 font-mono">Probability Engine</span>
          <span className="text-sm font-bold text-white font-mono">{Math.min(100, Math.max(0, prob))}%</span>
        </div>
        <div className="w-full bg-slate-800 rounded h-1.5 overflow-hidden">
          <div className="bg-blue-500 h-full" style={{ width: `${Math.min(100, Math.max(0, prob))}%` }}></div>
        </div>
      </div>

      <div className="grid grid-cols-3 gap-2 mb-4">
        <div className="bg-slate-950 p-2 rounded border border-slate-800">
          <div className="text-[9px] text-slate-500 uppercase tracking-widest mb-1">Exp Return</div>
          <div className="text-sm font-bold text-green-400 font-mono">{expectedReturn}</div>
        </div>
        <div className="bg-slate-950 p-2 rounded border border-slate-800">
          <div className="text-[9px] text-slate-500 uppercase tracking-widest mb-1">Risk / Reward</div>
          <div className="text-sm font-bold text-white font-mono">{riskReward}</div>
        </div>
        <div className="bg-slate-950 p-2 rounded border border-slate-800">
          <div className="text-[9px] text-slate-500 uppercase tracking-widest mb-1">Confidence</div>
          <div className="text-sm font-bold text-blue-400 font-mono">{confidence}</div>
        </div>
      </div>

      <div className="flex justify-between items-center text-[10px] font-mono text-slate-400 mb-4 bg-slate-950/50 p-2 rounded">
        <div className="text-center"><span className="text-slate-500 block">News</span> <span className="text-white">{newsScore}</span></div>
        <div className="text-center"><span className="text-slate-500 block">Tech</span> <span className="text-white">{techScore}</span></div>
        <div className="text-center"><span className="text-slate-500 block">Hist</span> <span className="text-white">{histScore}</span></div>
        <div className="text-center"><span className="text-slate-500 block">Liq</span> <span className="text-white">{liqScore}</span></div>
      </div>

      {/* Holding Period Badge */}
      <div className="mb-3">
        {(() => {
          const eventType = item.ai_analysis?.event_type || '';
          const holdingMap: Record<string, { icon: string; text: string; color: string }> = {
            'ORDER_WIN': { icon: '⚡', text: 'INTRADAY', color: 'text-amber-400 bg-amber-500/10 border-amber-500/30' },
            'FDA_APPROVAL': { icon: '⚡', text: 'INTRADAY', color: 'text-amber-400 bg-amber-500/10 border-amber-500/30' },
            'EARNINGS_BEAT': { icon: '📅', text: 'SWING (2-5 Days)', color: 'text-blue-400 bg-blue-500/10 border-blue-500/30' },
            'PROFIT_SURGE': { icon: '📅', text: 'SWING (2-5 Days)', color: 'text-blue-400 bg-blue-500/10 border-blue-500/30' },
            'CORPORATE_ACTION': { icon: '📅', text: 'SWING (2-5 Days)', color: 'text-blue-400 bg-blue-500/10 border-blue-500/30' },
            'ACQUISITION': { icon: '📅', text: 'SWING (1-2 Weeks)', color: 'text-purple-400 bg-purple-500/10 border-purple-500/30' },
            'MERGER': { icon: '📅', text: 'SWING (1-2 Weeks)', color: 'text-purple-400 bg-purple-500/10 border-purple-500/30' },
            'TURNAROUND': { icon: '📅', text: 'SWING (1-2 Weeks)', color: 'text-purple-400 bg-purple-500/10 border-purple-500/30' },
            'DEBT_REDUCTION': { icon: '📈', text: 'LONG TERM', color: 'text-emerald-400 bg-emerald-500/10 border-emerald-500/30' },
            'PROMOTER_BUYING': { icon: '📈', text: 'LONG TERM', color: 'text-emerald-400 bg-emerald-500/10 border-emerald-500/30' },
          };
          const holding = holdingMap[eventType] || { icon: '📅', text: 'SWING (2-5 Days)', color: 'text-blue-400 bg-blue-500/10 border-blue-500/30' };
          
          return (
            <div className={`inline-flex items-center gap-1.5 px-2.5 py-1 rounded-lg border text-[10px] font-mono ${holding.color}`}>
              <span>{holding.icon}</span>
              <span className="font-bold">{holding.text}</span>
            </div>
          );
        })()}
      </div>

      <div className="flex items-center justify-between text-[10px] font-mono uppercase tracking-widest">
        <span className="text-slate-500">Status</span>
        <span className="text-emerald-500 font-bold">PHASE 2 COMPLETE</span>
      </div>
    </div>
  );
}
